
---ADD
ALTER TABLESPACE STAGING_DATA ADD DATAFILE '+DATA_DG/DB/DATAFILE/staging_data_03.ora' SIZE 2147483648 AUTOEXTEND ON NEXT 10485760 MAXSIZE 32000M;


ALTER TABLESPACE TEMP ADD TEMPFILE 'F:\ORACLE\ORADATA\db\DATAFILE\TEMP_01.DBF' size 20M REUSE AUTOEXTEND ON;
ALTER TABLESPACE TEMPORARY ADD TEMPFILE 'F:\ORACLE\ORADATA\DB\DATAFILE\TEMPORARY01.ORA' size 10M REUSE AUTOEXTEND ON;
ALTER TABLESPACE TEMPORARY ADD TEMPFILE 'F:\ORACLE\ORADATA\DB\DATAFILE\TEMPORARY02.ORA' SIZE 1g REUSE AUTOEXTEND ON;

--DROP
ALTER TABLESPACE TEMP DROP TEMPFILE 'F:\ORACLE\ORADATA\DB\DATAFILE\TEMP01.DBF';
ALTER TABLESPACE TEMPORARY DROP TEMPFILE 'F:\ORACLE\ORADATA\DB\DATAFILE\TEMPORARY_01.ORA';
ALTER TABLESPACE TEMPORARY DROP TEMPFILE 'F:\ORACLE\ORADATA\DB\DATAFILE\TEMPORARY_02.ORA';


-----create


CREATE TABLESPACE ORACLE_DATA DATAFILE 'F:\ORACLE\ORADATA\DB\DATAFILE\ORACLE_DATA_01.ORA'  SIZE 1g REUSE AUTOEXTEND ON;
CREATE TABLESPACE ORACLE_INDEX DATAFILE 'F:\ORACLE\ORADATA\DB\DATAFILE\ORACLE_INDEX_01.ORA' SIZE 1g REUSE AUTOEXTEND ON;
