 ll
total 1574756
-rw-r--r--. 1 oracle oinstall 665864178 May  8 17:19 24.1.0.0.0_AgentCore_226.zip

[oracle@mytargetservername oraarchive]$ mkdir agent
[oracle@mytargetservername oraarchive]$ unzip 24.1.0.0.0_AgentCore_226.zip -d agent/.
Archive:  24.1.0.0.0_AgentCore_226.zip
  inflating: agent/./agentcore.bin
  inflating: agent/./agent.rsp
  inflating: agent/./agentDeploy.sh
  inflating: agent/./agentimage.properties
  inflating: agent/./unzip
  inflating: agent/./zip
   creating: agent/./plugins/
  inflating: agent/./plugins/oracle.sysman.si.discovery.plugin-24.1.1.0.0.farb
  inflating: agent/./plugins/oracle.sysman.emas.discovery.plugin-24.1.1.0.0.farb
  inflating: agent/./plugins/oracle.sysman.oh.agent.plugin-24.1.0.0.0.farb
  inflating: agent/./plugins/oracle.sysman.oh.discovery.plugin-24.1.0.0.0.farb
  inflating: agent/./plugins/oracle.sysman.xa.discovery.plugin-24.1.1.0.0.farb
  inflating: agent/./plugins/oracle.sysman.db.discovery.plugin-24.1.1.0.0.farb
  inflating: agent/./plugins.txt
[oracle@mytargetservername oraarchive]$ ll
total 1574760
-rw-r--r--. 1 oracle oinstall 665864178 May  8 17:19 24.1.0.0.0_AgentCore_226.zip
drwxr-xr-x. 3 oracle oinstall      4096 May  8 17:21 agent

[oracle@mytargetservername oraarchive]$ cd agent/
[oracle@mytargetservername agent]$ ll

######################################################################

[oracle@mytargetservername agent]$  cat agent.rsp
####################################################################
## copyright (c) 1999, 2012 Oracle. All rights reserved.          ##
##                                                                ##
## Specify values for the variables listed below to customize     ##
## your installation.                                             ##
##                                                                ##
## Each variable is associated with a comment. The comment        ##
## identifies the variable type.                                  ##
##                                                                ##
## Please specify the values in the following format:             ##
##                                                                ##
##         Type         Example                                   ##
##         String       "Sample Value"                            ##
##         Boolean      True or False                             ##
##         Number       1000                                      ##
##         StringList   {"String value 1","String Value 2"}       ##
##                                                                ##
## The values that are given as <Value Required> need to be       ##
## specified for a silent installation to be successful.          ##
##                                                                ##
##                                                                ##
## This response file is generated by Oracle Software             ##
## Packager.                                                      ##
###################################################################


#-------------------------------------------------------------------------------
#OMS_HOST:<String> OMS host info required to connect to OMS
#EM_UPLOAD_PORT:<String> OMS port info required to connect to OMS
#AGENT_REGISTRATION_PASSWORD:<String> Agent Registration Password needed to
#     establish a secure connection to the OMS.
#b_startAgent:<boolean> Agent will not be started after configuration if the value specified is false.
#AGENT_BASE_DIR=<String> Base directory of agent.
#AGENT_INSTANCE_HOME:<String> Agent instance home is the location of agent state directory.
#AGENT_PORT:<String> Agent port on which the agent process should be started.
#ORACLE_HOSTNAME:<String> Fully qualified domain name of host where is the agent is deployed.
#s_agentHomeName:<String>Customized Oracle home name for the agent home. Example: s_agentHomeName="agent12gR1"
#--------------------------------------------------------------------------------
#Following are mandatory parameters
#--------------------------------------------------------------------------------
OMS_HOST=OMS_Server_HOSTNAME
EM_UPLOAD_PORT=4903
AGENT_REGISTRATION_PASSWORD="Secret_Password"
#--------------------------------------------------------------------------------
#Following are optional parameters
#--------------------------------------------------------------------------------
#b_startAgent=<Value Unspecified>
AGENT_BASE_DIR=/u02/app/oracle/oraarchive/agent
AGENT_INSTANCE_HOME=/u02/app/oracle/oraarchive/agent/24ai
AGENT_PORT=3872
ORACLE_HOSTNAME=targetserverhostname
#s_agentHomeName=<Value Unspecified>
#-------------------------------------------------------------------------------
#s_agentSrvcName:<String> Sets the agent Service Name and this variable can be
#      used to overrite the agent service name calculated by the install. This is
#      required for only Windows.
#      Example:
#      s_agentSrvcName = "GridAgent"            ;  User specified value
#-------------------------------------------------------------------------------
#s_agentSrvcName=""
####################################################################################
#Please Don't change the values of these variables
####################################################################################
#-------------------------------------------------------------------------------
#EM_INSTALL_TYPE:<STRING> install type
#-------------------------------------------------------------------------------
EM_INSTALL_TYPE="AGENT"
[oracle@mytargetservername agent]$




######################################################################















 mkdir scratch
[oracle@mytargetservername agent]$ pwd
/u02/app/oracle/oraarchive/agent





[oracle@mytargetservername agent]$ ./agentDeploy.sh RESPONSE_FILE=/u02/app/oracle/oraarchive/agent/agent.rsp SCRATCHPATH=/u02/app/oracle/oraarchive/agent/scratch

cp: '/u02/app/oracle/oraarchive/agent/agentimage.properties' and '/u02/app/oracle/oraarchive/agent/agentimage.properties' are the same file
The space available is ....  1164820 MB
Executing command : /u02/app/oracle/oraarchive/agent/agent_24.1.0.0.0/jdk/jre/bin/java -classpath /u02/app/oracle/oraarchive/agent/agent_24.1.0.0.0/jlib/agentInstaller.jar:/u02/app/oracle/oraarchive/agent/agent_24.1.0.0.0/oui/modules/OraInstaller.jar     oracle.sysman.agent.installer.AgentInstaller /u02/app/oracle/oraarchive/agent/agent_24.1.0.0.0 /u02/app/oracle/oraarchive/agent /u02/app/oracle/oraarchive/agent $args -prereq
AGENT_ins home is:RESPONSE_FILE=/u02/app/oracle/oraarchive/agent/agent.rsporaclehome is:/u02/app/oracle/oraarchive/agent/agent_24.1.0.0.0
log loction is setlog
The oraclehome /u02/app/oracle/oraarchive/agent/agent_24.1.0.0.0

Validating oms host & port with url: https://omserverhostname:4903/empbs/genwallet
Validating oms host & port with url: http://omserverhostname:4903/empbs/genwallet
Return status:1-Either oms port passed is not valid or oms url is not accessible
ERROR: The Oracle Management Server (OMS) host and port specified via OMS_HOST and EM_UPLOAD_PORT is not available.  Pass in a valid hostname and port number for the OMS to successfully deploy the agent.

  Alternatively, you can do one of the following:
        1. Install the agent software only and configure the agent later once the OMS is available.  Installing just the software without configuring can be accomplished by passing the '-softwareOnly' argument to agentDeploy.sh and if windows pass the arguments to  agentDeploy.bat instead.  Configuring the agent after the software has been installed can be accomplished by passing the '-configOnly' argument to agentDeploy.sh and if platform is windows pass the arguments to  agentDeploy.bat.
         2. Force the configuration of the agent, even though the OMS is not available.  This can be accomplished by passing the '-forceConfigure' option to agentDeploy.sh and if windows pass the arguments to  agentDeploy.bat.

NOTE:  Forcing the configuration of the agent when the OMS is not available will configure the agent to use HTTP (non-secure) communication.  In order to properly establish secure HTTPS communication between the agent and the OMS, you will need to secure the agent after the OMS is available.

If you are passing 10.2.0.5.0 or 11.1.0.1.0 OMS_HOST and EM_UPLOAD_PORT then that is not supported. Pass in a valid hostname and port number of 12c OMS.
Validating the OMS_HOST & EM_UPLOAD_PORT has failed
